### PR TITLE
checks (some are object names, not sure if they work)

### PR DESCRIPTION
**Pull request by thegu5**
its used in a template rat, forgot which

### CODE REVIEW

**Comment by pandaninjas** [comment]
> its used in a template rat, forgot which

Used in CustomPayload's rat, used by FreeMoneyHub

**Comment by mindlesslydev** [comment]
A lot of the stuff in here is oddly specific, I think the checks should be kept as generic as possible.

**Comment by thegu5** [comment]
My reasoning was 'why not?'....
if you're sure they shouldn't be included, then I'll edit the pr

**Comment by mindlesslydev** [comment]
Personally I think it is better to remove the very specific strings as those programs should flag the generic checks anyway

**Comment by thegu5** [comment]
I removed everything name-based, including object names. Only generic urls/file paths are left now

**Comment by thegu5** [comment]
Side note, would this work for package names? Like

`package a.b.c.d` would be detected with a.b.c.d

**Comment by mindlesslydev** [comment]
> Edit: just realized this is template-specific, ignore
> 
> Side note, would this work for package names? Like
> 
> `package a.b.c.d` would be detected with a.b.c.d

Yes

**Comment by thegu5** [comment]
this pr should be good to merge now, it's just generic checks

**Comment by thegu5** [comment]
if checking for suspicious package names fits with the checks, then I'll either add them to this pr if it isn't merged or just make a new one

**Pull request merged**
